### PR TITLE
Add auto-updater for libXNVCtrl

### PR DESCRIPTION
**Pull request by guihkx**
Also update libXNVCtrl from 440.64 to 470.63.01

### CODE REVIEW

**Comment by gasinvein** [comment]
I'm not sure if it's safe to enable auto updates. There are beta, tesla and whatnot versions not for general public.

**Comment by guihkx** [comment]
That's very true. But AFAIK, doesn't the Flathub Bot open a pull request for review when there's an update? Therefore you could decide whether to merge it or not based on the [latest NVIDIA driver](https://www.nvidia.com/Download/index.aspx?lang=en-us) in production branch?

**Comment by gasinvein** [comment]
But how am I supposed to test if, say, nvidia-settings from vulkan-beta version works with drivers release version? I guess it actually does, but this still would need confirmation on each update.

I'm not against auto updates per se, but IMO we'd need to track more reliable version pointer than just the latest tag. Maybe track nvidia driver version in some distro, or something like this.

**Comment by guihkx** [comment]
>nvidia-settings from vulkan-beta version works with drivers release version?

Not to be pedantic, but this is only the libXNVCtrl library we're talking about. The nvidia-settings app has a much larger codebase than libXNVCtrl, which in contrast, is made of essentially [3 header files and 1 C file](https://github.com/NVIDIA/nvidia-settings/tree/main/src/libXNVCtrl).

Plus, I'm pretty sure libXNVCtrl is backwards compatible. I've been using MangoHud outside of Flatpak'd Steam as well, and at least on Arch Linux, the package version of [libxnvctrl](https://archlinux.org/packages/extra/x86_64/libxnvctrl/) is in-sync with the [main package of the NVIDIA driver](https://archlinux.org/packages/extra/x86_64/nvidia/), and so far I've had no breakages in MangoHud.

At the same time I say this, I also realize that libXNVCtrl gets so very little updates, that I think there's no harm in sticking to an older version for a little longer.

So feel free to close, I guess? 🤔

**Comment by gasinvein** [comment]
>I'm pretty sure libXNVCtrl is backwards compatible.

I think so, too, but not so sure. Ok, let's merge it and see.

**Pull request merged**
